// <auto-generated />
namespace BPMLab.Turboreactors.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Turboreactor_StartDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Turboreactor_StartDate));
        
        string IMigrationMetadata.Id
        {
            get { return "202206281524121_Turboreactor_StartDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
